AmericanWhitewater/wh2o-vue

- src/app/global/components/app-breadcrumbs/app-breadcrumbs.vue
Breadcrumbs currently show the text cursor, instead of the pointer feature they should.
cc/ @drewalth
> Pointer on Breadcrumb Items

- src/app/global/layout/layouts/layout-two-thirds.vue
UI tweak to ensure `layout-two-thirds` uses the full width once the components stack.
> make layout-two-thirds full width on small screens

- src/app/views/river-detail/map-tab/map-tab.vue
quick style change to ensure on `md` breakpoint once the sidebar drops to the bottom it's full-width
> quick styling fix on map detail page

- src/app/views/river-detail/main-tab/components/rapids-section/components/rapid-edit-modal.vue
@drewalth this resolves #71 *and* does something cool and new that I hadn't thought of -- if a rapid doesn't have an `rloc` (many seem not to) but it does have `distance`, I actually use the `distance` field to locate the rapid on the map! huzzah.
> fix rapid editing when rloc not present

- src/app/views/river-detail/river-detail.vue
Hey @drewalth this does two things (should probably have split the commits, sorry):
- transitions map banner to hidden on map tab
- fixes console error about duplicate navigation happening
- fixes issue where the tab menu (on the left) did not initialize with the correct tab dictated by the route on page load
> hide map banner on map tab and fix small router bug

- src/app/views/river-detail/main-tab/components/rapids-section/components/rapid-edit-modal.vue
- src/app/views/river-detail/shared/services/rapids.js
reinstates the "characteristics" multi-select and adds it to rapids graphql calls
fully resolves #92
> reinstate the characteristics field on rapids form

- src/app/views/river-detail/main-tab/components/rapids-section/components/nwi-map-editor.vue
- src/app/views/river-detail/shared/components/geometry-edit-modal/components/geometry-editor.vue
- src/app/views/river-index/components/nwi-map.vue
this uses refs to initialize all mapbox maps so that they work in the shadow DOM. It's something @drewalth did in the laravel deploy branch for one of the maps, but not all of them, so I applied that across the board for the development branch here. Can be cherry-picked into laravel-deploy until I get that branch fully compatible and able to be merged to development
> use refs to initialize all mapbox maps instead of ids

- src/app/views/river-detail/shared/services/rapids.js
- src/app/views/river-detail/shared/state/rapids/rapids.js
rloc was being overwritten by an empty rloc for existing rapids and our error handling logic was never being reached
> resolves rloc not populating and improves error handling

- src/app/views/river-index/components/nwi-map.vue
resolves the usability issue from https://github.com/AmericanWhitewater/wh2o/issues/1837 where the table didn't always update unless you re-moved the map
> ensure that the map table data is updated whenever sourcedata loads

- src/app/views/river-index/components/nwi-map.vue
un-hides other reaches from detail page map tab so that you can browse around the map on the detail page.
resolves https://github.com/AmericanWhitewater/wh2o/issues/1874
> dont hide other reaches on reach detail map tab

- package-lock.json
- package.json
- src/app/views/river-detail/main-tab/components/rapids-section/__tests__/__snapshots__/rapid-icon-bar.spec.js.snap
resolves: https://github.com/AmericanWhitewater/wh2o/issues/2012
> lock carbon/vue to 2.27.0 to un-break dropdowns

- src/app/global/services/human-readable.js
- src/app/views/river-detail/main-tab/components/beta-box/beta-box.vue
bug fix for #1965 
flow calculation always gets an invalid value to calculate last running
flow calculation gets correct value and some boundary checks
no
https://github.com/AmericanWhitewater/wh2o/issues/1965
> Fixes #1965 - updated as of a second ago now reports correct time.

- src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-icon-bar.vue
@drewalth this doesn't actually do anything other than make the rapid icon component not shit the bed now that we have `rapid` and `other`
> add "rapid" and "other" as recognizable types for rapids

- src/app/views/river-detail/components/geometry-edit-modal/components/geometry-editor.vue
- src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-map-editor.vue
- src/app/views/river-detail/components/map-banner.vue
- src/app/views/river-index/components/nwi-map.vue
Cleans up all map instances + resources when not needed.
[https://docs.mapbox.com/mapbox-gl-js/api/map/#map#remove](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#remove)
> Cleanup Map Instances

- .env.example
- src/app/plugins/apollo-client.js
- src/app/services/updatePost.js
- src/app/views/river-detail/components/gallery-tab.vue
- src/app/views/river-detail/components/image-gallery/__tests__/image-gallery.spec.js
- src/app/views/river-detail/components/image-gallery/image-gallery.vue
- src/app/views/river-detail/components/media-upload-form.vue
- removes VUE_APP_GRAPHQL_HTTP, not being used. replaced with VUE_APP_API_BASE_URL+"graphql"
- changes photo upload type to GALLERY and post type to PHOTO_UPLOAD to get correct ID 
- hides upload if user is not logged in
- refreshes gallery when upload is sent
- uploads the fields collected in the form when it updates the post
- code indicates that the gallery is updating a POST with the id of the reach being so the wrong post is getting updated and regular users are getting a post not authorized error
- code doesn't update fields from the form
- code uses two ways to indicate the graphql endpoint
- **What is the new behavior …
> fixes for photo upload form

- src/app/views/river-detail/components/gallery-tab.vue
addresses bug introduced by https://github.com/AmericanWhitewater/wh2o/issues/1797 that prevented gallery from loading if not logged in
> fix gallery so that it shows when users arent logged in

- src/app/global/components/post-update-modal/post-update-modal.vue
- src/app/services/updatePost.js
- src/app/views/river-detail/components/media-upload-form.vue
the photo upload changes to `updatePost` ended up breaking comments, which use that code without photos (since COMMENT is another type of post).
This fixes that, resolves https://github.com/AmericanWhitewater/wh2o/issues/2141
Ideally these should be entirely separate chunks of code but I'm not sure exactly how photo upload is going to evolve right now and these changes allow both, as they are currently, to continue working, so despite it being a little confusing I thought this would be easier than a bigger refactor with unknown future requirements.
> fix updatePost service to work for comments like it used to

- src/app/global/lib/gages/index.js
- src/app/views/river-detail/components/main-tab/components/beta-box/beta-box.vue
- fixes display on #1929 - matches correct gage
uses a zero-index gage in the reach gages to display flow on beta, though the rest of the logic uses a gage match 
uses correct gage
no
none
> fixes display on #1929 - matches correct gage

- src/app/assets/scss/components/_article-card.scss
- src/app/views/river-detail/components/main-tab/components/recent-alerts/components/side-bar-articles.vue
JavaScript was controlling the truncation of the news article in river detail. Swapped it to CSS.
> News truncation resizing

- src/app/assets/scss/components/_article-card.scss
The read more link can be handled with pure CSS, so these last few commits have been changing it to that. 
The "... Read More" link is positioned on top of the text. It's a little sloppy, but I think it's the way. 
I originally positioned the link away from the right edge, but text would peek through. I should have used padding so this pull request is only updating that.
> just a bit of padding to help clean up the read more link

- src/app/views/river-detail/components/flow-tab/flow-tab.vue
- Adds edit flows button if no gauge is associated with a river
* no way to edit flows if no gauge already exists
- edit flows buttons shows up on form in edit mode
* no
- no
> adds flow button back on a no-gauge page if in edit mode.

- src/app/views/river-detail/components/reports-tab/components/report-form.vue
ensures if gauge isn't selected, we default to "metric_id = 1" for trip reports so that runnable/high/low qualitative judgements display properly. https://github.com/AmericanWhitewater/wh2o/issues/2433
> fix trip report form to use visual gauge metric for visual readings

- src/app/global/components/multi-photo-uploader/multi-photo-uploader.vue
addresses https://github.com/AmericanWhitewater/wh2o/issues/2505. Turns out whenever a carbon file upload component emits `change`, it emits the entire list of files within it, so if some files are still pending, the code was calling upload an extra time (or more).
> fix issue where trip report multi photo uploader uploads duplicates

- src/app/global/lib/gages/index.js
- src/app/views/river-detail/components/flow-tab/components/flow-chart/flow-chart.vue
- src/app/views/river-detail/components/flow-tab/components/level-legend.vue
I am really not sure about this, the "range" definition stuff is extremely confusing -- as far as I can tell, there are clearly defined options for users defining ranges, but those options include duplicates:
I changed the front-end code to reflect the ranges that users are allowed to define today. I guess it's possible that misses ranges users were historically able to define, I have no idea. @ryangroth5 
I've tested this on a bunch of reaches and it seems to both a) work and b) resolve @AWKevin's issues (i.e. make this feature work)...but again, I do not feel like I have a real understanding of how this range stuff works, so maybe I'm missing something.
Addresses [Need Color Depiction of "Low Runnable" and "High Runnable" Flow Ranges](https://github.com/AmericanWhitewater/wh2o/issues/140 …
> first pass at fixing gauge range display

- src/app/views/river-detail/components/main-tab/components/reports-section/reports-section.vue
fixes piece of #2621 where photo ordering was not applied to the reports section of the main tab
> add photo sorting to reports-section of main tab

- src/app/global/components/app-toaster/app-toaster.vue
this resolves https://github.com/AmericanWhitewater/wh2o/issues/2656 by applying similar repositioning logic to that used to make modals work within the shadow dom mount
> add shadow-dom repositioning logic to app-toaster

- src/app/environment/index.js
- src/app/global/mixins/basemap-toggle.js
allows quicker configuration of ESRI basemaps via env var for [Migrate Away from Mapbox for Cost Savings#2715](https://github.com/AmericanWhitewater/wh2o/issues/2715)
> allow env var configuration of basemaps (within ESRI ecosystem)

- server_conf/jenkins/deploy.sh
ensures that vue deploy task in Jenkins fails obviously if it errors along the way (enhancement to close https://github.com/AmericanWhitewater/wh2o-vue/issues/539)
> ensure jenkins deploy fails if there are errors in script execution

- src/main.js
I was missing some configuration options that actually track page views using the router. I also don't want to pollute the analytics with beta traffic so I'm splitting those out.
> feature: configure matamo to use vue router

- src/app/views/river-detail/components/edit-flows/components/correlation-details.vue
https://github.com/AmericanWhitewater/aw-components/issues/594
> allow submission of edit flows form when just isPrimary is set

- src/app/views/river-detail/components/edit-flows/components/correlation-details.vue
addresses [Bug with display of edit flows interface for reach 2750](https://github.com/AmericanWhitewater/wh2o-vue/issues/618)
> fix styling to not break on edit flows page when comments are too long

- src/app/views/river-detail/components/edit-flows/components/correlation-details.vue
- src/app/views/river-detail/components/flow-tab/flow-tab.vue
> move gauge correlation comment above graph and add helper text to form
