AmericanWhitewater/wh2o-vue

src/app/views/river-index/components/nwi-map.vue, src/app/views/river-index/components/nwi-rivers-table.vue, src/app/views/river-index/river-index.vue, src/app/views/river-index/shared/state/river-index-data.js
work towards #23.
In addition to refactoring to use state, this also fixes the non-functional table entry highlighting when you mouse over the map.
=> transition map highlighting to vuex

src/app/views/river-detail/main-tab/main-tab.vue
fixes river detail main tab map
=> map hot fix

src/app/global/state/app-global-data.js, src/app/views/river-detail/main-tab/components/comments-section/__tests__/comments-section.spec.js, src/app/views/river-detail/main-tab/components/comments-section/comments-section.vue, src/app/views/river-detail/main-tab/components/side-bar/components/side-bar-alerts.vue
=> tests wip + toast viewed check removed

src/app/views/river-detail/main-tab/components/rapids-section/components/rapid-item.vue, src/app/views/river-detail/main-tab/components/rapids-section/components/rapid-media-uploader.vue
Just getting familiar with the project and dove in to fix to small UI papercuts
- Reduce bottom margin on each rapid
- Add distance units
cc/ @drewalth
=> UI Papercuts

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, README.md
Readme edit + setup for Code of Conduct and Contribution Guidelines docs.
=> readme + code of conduct + contributing documentation

src/app/assets/scss/components/_river-table.scss, src/app/views/river-index/components/nwi-rivers-table.vue, src/app/views/river-index/river-index.vue
improves usability of rivers table on nwi map. working towards #23
=> clean up nwi table display on river map

src/app/views/river-detail/__tests__/river-detail.spec.js, src/app/views/river-detail/river-detail.vue
Adds a few more tests for the river detail component.
=> Chore: River Detail Tests

.stylelintrc, src/app/assets/scss/abstracts/_mixins.scss, src/app/assets/scss/app.scss, src/app/assets/scss/base/_base.scss, src/app/assets/scss/base/_reset.scss, src/app/assets/scss/base/_typography.scss, src/app/assets/scss/components/_hr.scss, src/app/assets/scss/components/_river-table.scss, src/app/assets/scss/helpers/_bg-ui.scss, src/app/assets/scss/helpers/_cursor.scss, src/app/assets/scss/helpers/_sticky.scss, src/app/assets/scss/helpers/vue-animations/_fade.scss, src/app/assets/scss/helpers/vue-animations/_slide-fade.scss, src/app/assets/scss/theme/_color-themes.scss, src/app/assets/scss/vendor-ext/carbon-components/_bx--data-table.scss, src/app/assets/scss/vendor-ext/carbon-components/_bx--grid.scss, src/app/assets/scss/vendor-ext/carbon-components/_bx--loading.scss, src/app/assets/scss/vendor-ext/carbon-components/_bx--modal.scss, src/app/assets/scss/vendor/_carbon-components-helpers.scss, src/app/assets/scss/vendor/_carbon-components.scss
Adds rules to Stylelint configuration.
=> Chore: Stylelint Rules Adjusted

src/app/views/river-detail/main-tab/components/rapids-section/__tests__/rapids-section.spec.js, src/app/views/river-detail/main-tab/components/rapids-section/components/nwi-map-editor.vue, src/app/views/river-detail/main-tab/components/rapids-section/components/rapid-edit-modal.vue, src/app/views/river-detail/shared/services/rapids.js
want to weigh in on this approach and if you approve, merge it into your `feat/edit-rapid-map` branch and I can keep working on it from there?
=> new component for nwi map editor in rapid modal

package.json
=> Sentry + Carbon Vue Updated

.travis.yml, package.json, src/app/views/river-detail/main-tab/components/rapids-section/__tests__/__snapshots__/rapid-icon-bar.spec.js.snap
makes our node version consistent across package.json, Travis CI, and what @drewalth was using locally :)
=> specify node version 12 across the board

src/app/assets/scss/components/_river-table.scss, src/app/assets/scss/vendor-ext/carbon-components/_bx--data-table.scss, src/app/views/river-index/components/nwi-rivers-table.vue
This resolves #119 though it depends on https://github.com/AmericanWhitewater/wh2o/pull/1743. The branch in question is currently deployed on beta, so demoing this should work (unless that changes).
=> adjust nwi rivers table to show new fields, gauge reading and metric

.gitignore, .vscode/launch.json, src/app/global/components/app-toaster/app-toaster.vue, src/app/global/components/post-update-modal/post-update-modal.vue, src/app/global/components/utility-block/utility-block.vue, src/app/plugins/random-id.js, src/app/views/river-detail/gallery-tab/gallery-tab.vue, src/app/views/river-detail/main-tab/components/comments-section/__tests__/comments-section.spec.js, src/app/views/river-detail/main-tab/components/rapids-section/components/rapid-edit-modal.vue, src/app/views/river-detail/main-tab/components/side-bar/__tests__/side-bar-alerts.spec.js, src/app/views/river-detail/news-tab/__tests__/news-tab.spec.js, src/app/views/river-detail/river-detail.vue, src/app/views/river-detail/shared/components/alert-update-modal.vue, src/app/views/river-detail/shared/components/media-upload-form.vue
Adds UI feedback for upload status.
=> Media Upload Feedback

src/app/global/state/__tests__/app-global-data.spec.js, src/app/global/state/app-global-data.js
=> Chore: Misc Unit Tests

src/app/assets/scss/components/_river-table.scss, src/app/views/river-index/components/nwi-map.vue, src/app/views/river-index/components/nwi-rivers-table.vue
I think this resolves https://github.com/AmericanWhitewater/wh2o/issues/1762 but trying to test right now...
=> mildly simplify (and fix) the height logic for river map + table

src/app/views/river-detail/main-tab/components/rapids-section/rapids-section.vue
https://github.com/AmericanWhitewater/wh2o/issues/1779
=> fix issue where new rapid modal doesnt reload geom for other reaches

src/app/global/mixins/asset-url.js, src/app/views/river-detail/accidents-tab/accidents-tab.vue, src/app/views/river-detail/shared/services/accidents-tab.js, src/app/views/river-index/components/nwi-state-list.vue
Fix accident links and state list styling to remove scroll bar
=> made accidents work, little styling on state list

src/app/views/river-detail/shared/components/image-gallery/image-gallery.vue, src/app/views/river-detail/shared/services/gallery-tab.js
resolves https://github.com/AmericanWhitewater/wh2o/issues/1809
=> add file_size to image gallery display

src/app/views/river-detail/shared/state/main-tab/alerts-data.js, src/app/views/river-detail/shared/state/main-tab/comments-data.js, src/app/views/river-detail/shared/state/news-tab/news-tab-data.js
resolves https://github.com/AmericanWhitewater/wh2o/issues/1831
=> fix safari date parse issue by using moment

src/app/global/components/post-update-modal/post-update-modal.vue
resolves https://github.com/AmericanWhitewater/wh2o/issues/1839
=> fix new alert modal form from river detail main tab

src/app/views/river-detail/shared/services/gallery-tab.js
resolves residual complaint on https://github.com/AmericanWhitewater/wh2o/issues/1832
=> reverse order for image query on detail gallery

src/app/views/river-detail/shared/components/geometry-edit-modal/components/geometry-editor.vue
=> revert back to original basemaps (not mixin) for geometry editor

src/app/views/river-detail/credits-tab/credits-tab.vue
resolves https://github.com/AmericanWhitewater/wh2o/issues/1853
=> fix occasional error on contributors tab

src/app/views/river-detail/main-tab/components/recent-alerts/components/side-bar-articles.vue
point news articles from main tab to existing legacy article display, same as news tab
=> fix news article link from main tab

src/app/views/river-index/components/nwi-map.vue, src/app/views/river-index/shared/state/river-index-data.js
resolves https://github.com/AmericanWhitewater/wh2o/issues/1794
=> store map bounds in state for global nwi map

src/app/views/river-detail/accidents-tab/accidents-tab.vue
resolves https://github.com/AmericanWhitewater/wh2o/issues/1873
=> fix accidents tab so that it always retrieves accidents when created

src/app/views/river-index/components/nwi-map-styles.js
resolves https://github.com/AmericanWhitewater/wh2o/issues/1899
=> fix map zoom styling to not interpolate reach segments to invisible

src/app/assets/scss/views/river-detail/components/_geometry-edit-modal.scss, src/app/views/river-detail/shared/components/geometry-edit-modal/components/geometry-editor.vue
resolves https://github.com/AmericanWhitewater/wh2o/issues/1904
=> add reset button to map editor

src/app/views/river-detail/main-tab/components/beta-box/beta-box.vue, src/app/views/river-detail/main-tab/components/beta-box/components/beta-box-edit-modal.vue, src/app/views/river-detail/map-tab/components/info-panel/info-panel.vue, src/app/views/river-detail/map-tab/map-tab.vue, src/app/views/river-detail/river-detail.vue, src/app/views/river-index/components/nwi-map-styles.js, src/app/views/river-index/components/nwi-map.vue, src/app/views/river-index/components/nwi-rivers-table.vue, src/app/views/river-index/river-index.vue
List issues included below:
- [Edit on river detail opens prior reach edit](https://github.com/AmericanWhitewater/wh2o/issues/1878)
- [MANY rivers/sections seem to be missing](https://github.com/AmericanWhitewater/wh2o/issues/1891) **NOTE: this depends on a release in wh2o of https://github.com/AmericanWhitewater/wh2o/pull/1946**
=> Release 2020-10-26

src/app/global/mixins/map-helpers.js
resolves AmericanWhitewater/wh2o#1974
=> fix geometry editor map centering when no geospatial info exists

src/app/views/river-detail/flow-tab/components/gage-chart-controls.vue
Fixes #1888
Fixed to CFS
Uses the reach's gauge metric rather than fixed to CFS
none
none
=> Fixes #1888 - gauge metric not set on flow page.

src/app/views/river-detail/shared/components/geometry-edit-modal/components/geometry-editor.vue
resolves https://github.com/AmericanWhitewater/wh2o/issues/1905
=> split NHD multilinestrings into lines for graph calculations

src/app/services/createRapid.js, src/app/services/updateRapid.js, src/app/store/modules/river-rapids.js, src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-item.vue
front end half of fix for https://github.com/AmericanWhitewater/wh2o/issues/2045
=> allow rapid viewing, sorting, and saving to work without location/distance

src/app/store/modules/river-rapids.js
per feedback from @AWKevin on https://github.com/AmericanWhitewater/wh2o/issues/2045
=> put rapids with no location at the end of the list

src/app/services/getGage.js, src/app/services/getGageReadings.js, src/app/services/getReachGages.js, src/app/views/river-detail/components/flow-tab/components/flow-chart/flow-chart.vue, src/app/views/river-detail/components/flow-tab/components/flow-stats/flow-stats.vue, src/app/views/river-detail/components/flow-tab/components/gage-chart-controls.vue, src/app/views/river-detail/components/flow-tab/flow-tab.vue
This is to fix many of the issues related to display flows in the SPA 
fixes tickets: 
#2032
#1889
#1770
#1964
See the project board. 
Adds ability to choose between metrics that are available for a gauge
no
=> Flow fixes Part 2!

src/app/services/getReach.js, src/app/views/river-detail/components/flow-tab/components/flow-stats/flow-stats.vue, src/app/views/river-detail/components/flow-tab/components/gage-chart-controls.vue, src/app/views/river-detail/components/flow-tab/flow-tab.vue, src/app/views/river-detail/components/main-tab/components/beta-box/__tests__/beta-box.spec.js, src/app/views/river-detail/components/main-tab/components/beta-box/beta-box.vue
Bugfix 
Gages in beta box are simply the first gauge
Gages are selected based on reach associations 
no
=> Fixes arbitrary gauge selection in beta box & corrects current reading

src/app/http/index.js
Adds interceptor to better handle errors from the API.
=> Adds Error Interceptor

src/app/global/mixins/asset-url.js, src/app/views/river-detail/components/flow-tab/components/flow-stats/flow-stats.vue, src/app/views/river-detail/components/flow-tab/flow-tab.vue
Fixes links to go to old gauge detail 
goes to unfinished spa gauge detail 
=> point gauge detail links to old page

src/app/views/river-detail/components/main-tab/components/beta-box/beta-box.vue
A bugfix 
https://github.com/AmericanWhitewater/wh2o/issues/2075
fixes it. 
=> Fixes beta box using wrong updated field

src/app/services/photoFileUpdate.js, src/app/views/river-detail/components/gallery-tab.vue, src/app/views/river-detail/components/media-upload-form.vue
Addresses [https://github.com/AmericanWhitewater/wh2o/issues/1797](https://github.com/AmericanWhitewater/wh2o/issues/1797).
=> Upload Rewired

package-lock.json, package.json
should resolve https://github.com/AmericanWhitewater/wh2o/issues/2079 (and the duplicate issue https://github.com/AmericanWhitewater/wh2o/issues/2069)
=> downgrade versions of @carbon/vue but not all the way to original

src/app/services/photoFileUpdate.js, src/app/views/river-detail/components/gallery-tab.vue, src/app/views/river-detail/components/media-upload-form.vue
lol @drewalth here it is again, @ryangroth5 wants it on beta so he can deal w/ the permissions thing more easily
=> reinstate drew's single photo upload logic

src/app/store/modules/river-projects.js
resolves https://github.com/AmericanWhitewater/wh2o/issues/2129
=> fix projects state logic

src/app/views/river-detail/components/gallery-tab.vue
with any luck, this is the last fix for https://github.com/AmericanWhitewater/wh2o/issues/1797
=> fix image upload modal cancelling

src/app/plugins/random-id.js
possibly resolves https://github.com/AmericanWhitewater/wh2o/issues/2149, testing further
=> fix usage of nanoid to match documentation

src/app/store/modules/river-credits.js
Fixes revisions on river page
revisions are not displayed 
revisions are displayed 
no
=> Fixes reach credits/revisions

src/app/global/components/confirm-delete-modal/confirm-delete-modal.vue, src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-item.vue, src/app/views/river-detail/components/main-tab/components/rapids-section/rapids-section.vue
potentially resolves https://github.com/AmericanWhitewater/wh2o/issues/2035... have to test it on beta as the problem was not reproducible locally
=> refactor rapid delete modal in effort to fix display issue

src/app/views/river-index/river-index.vue
=> switched map and nav items sections of HTML

src/app/views/river-detail/components/flow-tab/flow-tab.vue
=> fixes the gaugeinfo warning on load

src/app/views/river-detail/components/flow-tab/flow-tab.vue, src/app/views/river-detail/components/main-tab/components/recent-alerts/components/side-bar-articles.vue
=> hotfix for gauge

src/app/services/getStateList.js, src/app/store/modules/river-index.js, src/app/views/river-index/components/nwi-state-list.vue, src/app/views/river-index/river-index.vue
uses new state logic to display international regions that have rivers in them. @mattanger put this in with your existing states table and logic so you're probably the best person to review
https://github.com/AmericanWhitewater/wh2o/issues/1670
=> display international river regions below us states

src/app/assets/scss/components/_article-card.scss
Please advise on git stuff. I removed this line but was surprised it was there and half expect it to still be in beta after this is approved.
=> removed bad line of css

src/app/views/river-detail/river-creator.vue
- adds the ability to see why reach creation failed (if the error is exposed)
* It says "error"
- It gives the error message from the client
- shouldn't.
- Addresses #1848
=> adds reach creation errors to the error message displayed.

src/app/views/river-detail/components/media-upload-form.vue
- now shows upload errors (if any)
- also puts a spinner on the screen when upload is pending.
- no spinner and confused people
- less confused people
- no
=> Adds error message display on upload.

src/app/global/mixins/index.js, src/app/global/mixins/reach-published-states.js, src/app/services/createReach.js, src/app/services/getReach.js, src/app/services/updateReach.js, src/app/views/river-detail/components/reach-title-edit-modal.vue, src/app/views/river-detail/river-creator.vue
this deals with an immediate issue for https://github.com/AmericanWhitewater/wh2o/issues/1848, although there is still some pending backend question.
I don't think this is really the workflow that the "status" field was built for, so it leaves some open questions. I'll try to explain it on the issue itself for @AWKevin to chime in on once this gets merged
=> add dropdown to reach creator and reach edit for publishing status

src/app/views/river-detail/components/credits-tab.vue
Changed the "Revision Comment" to be regular text.
=> revision comment resize

src/app/store/modules/river-events.js, src/app/views/river-detail/components/flow-tab/components/releases-table.vue
Bug fix
Release table in flow tab was broken, I think it's good now
=> 2 line bug fix on release table

src/app/global/components/content-editor/content-editor.vue, src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-edit-modal.vue
this resolves testing issues identified for https://github.com/AmericanWhitewater/wh2o/issues/2142
=> change tinymce editor toolbar for rapid description edits

src/app/views/river-index/components/nwi-map.vue
resolves https://github.com/AmericanWhitewater/wh2o/issues/2246
=> reinstate mapbox attribution on national map

src/app/views/river-detail/components/media-upload-modal.vue
resolves Safari editing bug for https://github.com/AmericanWhitewater/wh2o/issues/2159
=> use moment to parse photo_date for photo edit to avoid Safari error

src/app/views/river-index/components/nwi-rivers-table.vue
re-fixes https://github.com/AmericanWhitewater/wh2o/issues/2230
=> use router-link instead of a for nwi-rivers-table links

src/app/store/modules/river-events.js, src/app/views/river-detail/components/flow-tab/components/releases-table.vue, src/app/views/river-detail/components/main-tab/components/beta-box/beta-box.vue
corrects a bug in determining the next or last date
next release date is wrong
latest listed release date is shown as next release date
no
none
=> Addresses #1830

src/app/views/river-index/components/nwi-map.vue
sends the csrf header with tile requests
doesn't send it 
sends it
no
#1963
=> fixes #1963 secure tile endpoint client changes.

src/app/views/river-index/river-index.vue
continues to address https://github.com/AmericanWhitewater/wh2o/issues/2207
=> add auto-scroll button to river table on mobile

package-lock.json, package.json, src/app/views/river-detail/components/geometry-edit-modal/components/geometry-editor.vue
resolves https://github.com/AmericanWhitewater/wh2o/issues/2108 by using the new NLDI api
sorry for the linting mess on the one file, hopefully we conclusively sort that out soon
=> rewrite geometry editor to use NLDI api

package-lock.json, package.json, src/app/views/river-detail/components/geometry-edit-modal/components/geometry-editor.vue
This reverts commit c6140c7576e4df3e8e97a1e7ef4d1a11bf29fa36.
=> temporary rollback of NLDI changes for release

src/app/views/river-detail/components/media-upload-modal.vue
fixes https://github.com/AmericanWhitewater/wh2o/issues/2328
=> fix #2328 by ensuring form resets after photo upload

src/app/services/canCreateReach.js, src/app/store/modules/river-detail.js, src/app/views/river-detail/river-creator.vue
adds create check after draw of reach 
uses arbitrary permissions on client side to see if createReach will be successfull
uses a backend check
no
#2346
=> adds a backend check to see if user has reach submit permission

src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-map-editor.vue
resolves https://github.com/AmericanWhitewater/wh2o/issues/2412
=> fix new point addition in rapid creation dialog

src/app/services/getReach.js, src/app/services/updateReach.js, src/app/views/river-detail/components/reach-title-edit-modal.vue, src/app/views/river-detail/river-detail.vue, src/app/views/river-index/components/nwi-rivers-table.vue
resolves https://github.com/AmericanWhitewater/wh2o/issues/2170
=> add reach altname to UX

src/app/views/river-index/components/nwi-map-styles.js
map label update for https://github.com/AmericanWhitewater/wh2o/issues/2170
=> adjust map style to include reach altname in map label

src/app/views/river-detail/components/main-tab/components/beta-box/beta-box.vue, src/app/views/river-detail/components/main-tab/components/beta-box/components/beta-box-edit-modal.vue
quick fix re: https://github.com/AmericanWhitewater/wh2o/issues/1180
=> fix merge error that broke beta box updating

src/app/services/updateReach.js
=> fix merge typo

src/app/router/index.js
for https://github.com/AmericanWhitewater/wh2o/issues/1935
=> adjust router scrollBehavior so that river detail tabs open at the top

src/app/global/components/multi-photo-uploader/multi-photo-uploader.vue
for https://github.com/AmericanWhitewater/wh2o/issues/2447
=> ensure post date is saved on photos when a trip report is edited

src/app/global/components/table-pagination/table-pagination.vue, src/app/services/getReachReports.js, src/app/store/modules/river-reports.js, src/app/views/river-detail/components/image-gallery/image-detail.vue, src/app/views/river-detail/components/reports-tab/components/report-form.vue, src/app/views/river-detail/components/reports-tab/reports-tab.vue, src/app/views/river-detail/river-detail.vue
for https://github.com/AmericanWhitewater/wh2o/issues/2423
=> implement paging interface for reach reports

src/app/views/river-detail/components/image-gallery/image-update-modal.vue
for https://github.com/AmericanWhitewater/wh2o/issues/2458
=> ensure post_type is set properly when editing images in the gallery

src/app/global/components/image-selector-modal/image-selector-modal.vue
fixes https://github.com/AmericanWhitewater/wh2o/issues/2479
=> fix rapid image selector to work with new photos endpoint

src/app/views/river-detail/river-detail.vue
first pass at small redesign for https://github.com/AmericanWhitewater/wh2o/issues/2482
=> rearrange and rename reach title edit and reach delete buttons

src/app/views/river-detail/components/main-tab/components/recent-alerts/components/side-bar-documents.vue
fixes link for document in sidebar
doesn't work
does work
no
=> fixes 2478

src/app/views/river-detail/__tests__/gallery-tab.spec.js, src/app/views/river-detail/components/gallery-tab/gallery-tab.vue, src/app/views/river-detail/components/gallery-tab/image-gallery/image-update-modal.vue
addresses https://github.com/AmericanWhitewater/wh2o/issues/2492 by removing file upload capability from the gallery upload form (just editing now) and redirecting users to the trip report interface.
=> remove gallery image upload capability and direct users to trip reports

src/app/views/river-detail/components/reports-tab/components/report-form.vue
fixes issue @AWKevin found while testing https://github.com/AmericanWhitewater/wh2o/issues/2492 -- Pit river gauge data issue (unclear if this is a database problem or not) was breaking the trip report form.
=> resolve gage id missing issue for new trip report link

src/app/global/mixins/format-date.js
front-end display tweak for https://github.com/AmericanWhitewater/wh2o/issues/2529
=> add special logic to interpret jan 1st, 1990 as "unknown date"

src/app/services/searchReachMap.js, src/app/views/river-detail/components/main-tab/components/beta-box/beta-box.vue, src/app/views/river-index/components/nwi-rivers-table.vue
another component of https://github.com/AmericanWhitewater/wh2o/issues/2229
=> adjust reach summary flow display to account for gauge_estimated

src/app/global/mixins/format-date.js
tweak accounts for prod/beta inconsistencies regarding https://github.com/AmericanWhitewater/wh2o/issues/2529 and just makes it slightly more resilient
=> make any TR date before 1910 show up as "unknown date"

src/app/views/river-detail/components/flow-tab/components/gage-summary.vue, src/app/views/river-detail/components/flow-tab/flow-tab.vue, src/app/views/river-detail/components/main-tab/components/beta-box/beta-box.vue
aligns use of excluded flag with behavior of state summary
ignores excluded flag.
aligns use of excluded flag with behavior of state summary
no
aligns use of excluded flag with behavior of state summary
=> fixes use of the excluded flag on the SPA #2463

src/app/global/mixins/shadow-dom-fixed-height-offset.js
=> tweak shadow dom modal height offsetting

src/app/views/river-detail/components/main-tab/components/reports-section/reports-section.vue
https://github.com/AmericanWhitewater/wh2o/issues/2593
=> ensure new trip report button only shows if user is logged in

src/app/global/components/multi-photo-uploader/multi-photo-uploader.vue, src/app/global/mixins/article-helper.js, src/app/views/river-detail/components/gallery-tab/image-gallery/image-gallery.vue, src/app/views/river-detail/components/gallery-tab/image-gallery/image-update-modal.vue, src/app/views/river-detail/components/reports-tab/components/report-image-gallery.vue, src/app/views/river-detail/components/reports-tab/components/report-preview.vue
https://github.com/AmericanWhitewater/wh2o/issues/2587
=> update (nearly) all image references to use medium instead of thumb

src/app/views/river-index/components/nwi-map.vue
hopefully addresses https://github.com/AmericanWhitewater/wh2o/issues/2143 but pending comment from Kevin on that before merging
=> remove legacy code tracking user location for nwi map

src/app/store/modules/river-reports.js, src/app/views/river-detail/components/reports-tab/components/edit-report.vue, src/app/views/river-detail/components/reports-tab/components/report-detail.vue
fix for Safari in https://github.com/AmericanWhitewater/wh2o/issues/2621
=> use moment instead of Date to parse photo created_ats and fix safari

src/app/views/river-detail/components/news-tab/news-tab.vue
follow-up PR for https://github.com/AmericanWhitewater/wh2o/issues/2592
=> show "Login to add an alert" button for logged out users on news tab

src/app/global/components/multi-photo-uploader/multi-photo-uploader.vue
https://github.com/AmericanWhitewater/wh2o/issues/2616
=> add label and clarify text for multi file upload form field

src/app/global/mixins/format-date.js
addresses https://github.com/AmericanWhitewater/wh2o-vue/issues/502
=> fix issue with accident tab date error

src/app/global/mixins/poi-classes.js, src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-edit-modal.vue
addresses https://github.com/AmericanWhitewater/wh2o/issues/2694
**RELEASE NOTE**: requires https://github.com/AmericanWhitewater/wh2o/pull/2708
=> update POI class list to I-VI with +s and -s

src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-edit-modal.vue
small issue with the code fixing https://github.com/AmericanWhitewater/wh2o/issues/2694
=> remove reference to no longer existing function

src/app/global/mixins/poi-classes.js, src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-edit-modal.vue
addresses bug in https://github.com/AmericanWhitewater/wh2o/issues/2713
=> fix poi class input so that an empty string cannot be submitted

src/app/global/mixins/poi-classes.js, src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-edit-modal.vue
- [New River Feature Failed to Load #2713](https://github.com/AmericanWhitewater/wh2o/issues/2713) *hotfix*
=> release-20230220

src/app/views/river-detail/river-detail.vue
fixes bug introduced in https://github.com/AmericanWhitewater/wh2o/issues/2345
=> fix display of Add Featured Image for pages with no existing image

package-lock.json
fixing annoying and subtle change introduced by merging a dependabot PR which screws up our git approach to deploys
=> commit locally generated package-lock to fix deploys post dependabot pr

src/app/global/components/table-pagination/table-pagination.vue
https://github.com/AmericanWhitewater/wh2o-vue/issues/527
Not 100% clear this is the issue Charlie was citing, but it's clearly an issue regardless
=> adjust style to display gallery pagination on mobile

src/app/global/components/content-editor/content-editor.vue
resolves https://github.com/AmericanWhitewater/wh2o/issues/2739
=> change tinymce so it doesnt automatically convert URLs to relative

src/app/views/river-detail/components/flow-tab/components/flow-stats/flow-stats.vue, src/app/views/river-detail/components/flow-tab/flow-tab.vue
https://github.com/AmericanWhitewater/wh2o-vue/issues/549
=> ensure gauge reading and "current" match on the flow tab

package-lock.json
this brings the repo in sync with what was being generated by beta and prod, thus resolving https://github.com/AmericanWhitewater/wh2o-vue/issues/558.
*NOTE*: all developers should go through the steps outlined in #558 and *please* do not accidentally commit changes to package-lock.json.
=> cache cleared package-lock update

package-lock.json, package.json, src/main.js
Integrates matamo tracking for vue.
Currently, we do not do any tracking for matamo. I would like to try doing tracking with matamo to see if it will meet our needs.
No breaking changes.
=> integrate matamo

src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-edit-modal.vue
should resolve https://github.com/AmericanWhitewater/wh2o/issues/2796
=> resolve issue where editing rapids was unexpectedly changing photos

README.md, src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-edit-modal.vue
- [When Editing a Feature Like a Rapid the Photo Gets Replaced With a Different One](https://github.com/AmericanWhitewater/wh2o/issues/2788#top)
=> release-20240328

package-lock.json, package.json, src/main.js
=> revert matomo

src/app/views/river-detail/components/main-tab/components/beta-box/beta-box.vue
resolves https://github.com/AmericanWhitewater/wh2o-vue/issues/594
=> fix beta box to use gagesWithGauge instead of gages

README.md, package-lock.json, package.json, src/app/views/river-detail/components/main-tab/components/beta-box/beta-box.vue, src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-edit-modal.vue, src/main.js
Includes:
- revert matomo
- #594 
Note: changelog looks a bit weird because the last release was squash-merged, which our current github setup relies on us not doing for releases (redesigning – or rather designing – our git strategy should be on the todo list!)
=> release-20240529

src/app/views/river-detail/components/main-tab/components/beta-box/beta-box.vue
https://github.com/AmericanWhitewater/wh2o-vue/issues/606
=> fix beta box to function when gauge has reading but not correlation

src/app/views/river-detail/components/edit-flows/components/correlation-details.vue
This reverts commit 16f770cce46fe9c930dd7efecfe10d5154960a67.
=> Revert "allow submission of edit flows form when just isPrimary is set"

src/app/views/river-detail/components/flow-tab/flow-tab.vue
addresses https://github.com/AmericanWhitewater/wh2o-vue/issues/600
=> add month option to flow tab interface

src/app/views/river-detail/components/edit-flows/components/correlation-details.vue
- [Bug with display of edit flows interface for reach 2750](https://github.com/AmericanWhitewater/wh2o-vue/issues/618)
=> 20241210-release

src/app/views/river-detail/components/main-tab/components/recent-alerts/recent-alerts.vue
addresses https://github.com/AmericanWhitewater/wh2o/issues/2595 and https://github.com/AmericanWhitewater/wh2o/issues/2576, at least partially
=> limit main tab news to one year old and alerts to two years old

src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-map-editor.vue
hopefully addresses @riversandcreeks issue where POIs snap accidentally while making non-map edits
=> infer snap mode setting from existing point on poi edit

src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-edit-modal.vue, src/app/views/river-detail/components/main-tab/components/rapids-section/components/rapid-map-editor.vue
- adjust rapid edit interface to only use 8 digit precision for lat/lng to line up with backend
=> 20250527-release
